### ISSUE TITLE
Make gensokyo:roe a CompliantSwitch

### ISSUE THREAD

**Issue by Ameliorate** [Ameliorate/KANI#1]
I need to ask permission first.

**Comment by patrick1bauer** [comment]
Done. The new switch should be made slightly bigger and maybe moved to the inside of the main rail station to accommodate other rails in gensokyo:roe

**Comment by Ameliorate** [comment]
34ce05aaa5c1eceda88ea83dd2d91f60122960db makes the above ground station compliant
