### ISSUE TITLE
ch1prempire -> hjaltland stops at j:piria

### ISSUE THREAD

**Issue by Ameliorate** [Ameliorate/KANI#125]
Might be because of a minecart there, yergo wasn't sure.

**Comment by CredixYt** [comment]
Managed to reach `j:pend` using `/dest oasis j:piria j:pend`. I think it is safe to assume it yergo was stopped by another minecart.

Note: I've added 2 powered rails to `j:pend` after it turns towards `j:piria` as the minecart could barely reach the existing powered rails.

**Comment by Ameliorate** [comment]
Sounds good. Thanks for taking a look.
