### ISSUE TITLE
Investigate ways to reduce size of routes.json

### ISSUE THREAD

**Issue by Ameliorate** [Ameliorate/KANI#41]
Right now, it's 1 megabyte. As more destinations are added, the size of the file will increase exponentally.

**Comment by Gjum** [comment]
do you want me to rewrite the routing in javascript?

or convert the main logic using one of these https://yasoob.me/2019/05/22/running-python-in-the-browser/

**Comment by Metriximor** [comment]
If you're gona go with a http api server I can't recommend FastAPI enough

**Comment by stzups** [comment]
[amel.pw/kani](https://amel.pw/kani) reports it is using nginx. Have you looked in to enabling compression? [https://docs.nginx.com/nginx/admin-guide/web-server/compression/](https://docs.nginx.com/nginx/admin-guide/web-server/compression/)

gzip and other modern compression algorithms can have a massive impact on json files and similar. 

If that isn't enough, then you may consider ditching text files and serving a custom binary blob. This would be the fastest and most space efficient option, which I have experience implementing :)

**Comment by Ameliorate** [comment]
For now I enabled compression on amel.pw. In the future, I'd like to rewrite routing in json, or maybe typescript. I would do that with a full redesign of the website, though.
