### ISSUE TITLE
A* isn't a good algorithm for the compute program

### ISSUE THREAD

**Issue by Ameliorate** [Ameliorate/KANI#46]
The compute program sometimes generates suboptimal routes. Instead of A*, something like Dijkstra's algorithm would be better

**Comment by Gjum** [comment]
A* is [optimal](https://en.wikipedia.org/wiki/A*_search_algorithm#Admissibility), you can't get better routes just by using a less efficient algorithm. What's possible though is that your heuristic isn't "admissible"; I haven't looked yet but as long as you use euclidean distance then A* should return the optimal route. If you have really weird rail links, you could try using a different metric for the actual edge weights though (not the heuristic), such as taxicab or just 2*euclidean.
> When A* terminates its search, it has found a path from start to goal whose actual cost is lower than the estimated cost of any path from start to goal through any open node.

**Comment by Ameliorate** [comment]
I'll look into the heuristic
