### ISSUE TITLE
Cannibalize MTA Rail System

### ISSUE THREAD

**Issue by Ameliorate** [Ameliorate/KANI#64]
- [x] MTA Redline
- [x] MTA East
- [x] MTA West

**Comment by Ameliorate** [comment]
MTA East becomes MTA Minor: 9c3169fcb9c090e1a76dd8ea60d3d83c7544c9f0

**Comment by Ameliorate** [comment]
MTA East: 09601dcdcaf9887713da47dfc34643bc13d783c9

**Comment by Metriximor** [comment]
Unrelated but u could have said "Kannibalize" instead of "Cannibalize" and I can't get over this wasted potential

**Comment by Ameliorate** [comment]
oh no what have i done

**Comment by Ameliorate** [comment]
Redline: 58e72c1aaf43b9829b1cbfa7a703c6a8bd4e7785 4a9985490be211a3b1ff5196e77679c8d5ee0859
